/** ISO 3166-1 country codes and English short names. Not a political statement; official ISO list. */
export const ISO_3166_1_COUNTRIES: ReadonlyArray<{ isoAlpha2: string; isoAlpha3: string; name: string }> = [
  { isoAlpha2: 'AD', isoAlpha3: 'AND', name: 'Andorra' },
  { isoAlpha2: 'AE', isoAlpha3: 'ARE', name: 'United Arab Emirates' },
  { isoAlpha2: 'AF', isoAlpha3: 'AFG', name: 'Afghanistan' },
  { isoAlpha2: 'AG', isoAlpha3: 'ATG', name: 'Antigua and Barbuda' },
  { isoAlpha2: 'AI', isoAlpha3: 'AIA', name: 'Anguilla' },
  { isoAlpha2: 'AL', isoAlpha3: 'ALB', name: 'Albania' },
  { isoAlpha2: 'AM', isoAlpha3: 'ARM', name: 'Armenia' },
  { isoAlpha2: 'AO', isoAlpha3: 'AGO', name: 'Angola' },
  { isoAlpha2: 'AQ', isoAlpha3: 'ATA', name: 'Antarctica' },
  { isoAlpha2: 'AR', isoAlpha3: 'ARG', name: 'Argentina' },
  { isoAlpha2: 'AS', isoAlpha3: 'ASM', name: 'American Samoa' },
  { isoAlpha2: 'AT', isoAlpha3: 'AUT', name: 'Austria' },
  { isoAlpha2: 'AU', isoAlpha3: 'AUS', name: 'Australia' },
  { isoAlpha2: 'AW', isoAlpha3: 'ABW', name: 'Aruba' },
  { isoAlpha2: 'AX', isoAlpha3: 'ALA', name: 'Åland Islands' },
  { isoAlpha2: 'AZ', isoAlpha3: 'AZE', name: 'Azerbaijan' },
  { isoAlpha2: 'BA', isoAlpha3: 'BIH', name: 'Bosnia and Herzegovina' },
  { isoAlpha2: 'BB', isoAlpha3: 'BRB', name: 'Barbados' },
  { isoAlpha2: 'BD', isoAlpha3: 'BGD', name: 'Bangladesh' },
  { isoAlpha2: 'BE', isoAlpha3: 'BEL', name: 'Belgium' },
  { isoAlpha2: 'BF', isoAlpha3: 'BFA', name: 'Burkina Faso' },
  { isoAlpha2: 'BG', isoAlpha3: 'BGR', name: 'Bulgaria' },
  { isoAlpha2: 'BH', isoAlpha3: 'BHR', name: 'Bahrain' },
  { isoAlpha2: 'BI', isoAlpha3: 'BDI', name: 'Burundi' },
  { isoAlpha2: 'BJ', isoAlpha3: 'BEN', name: 'Benin' },
  { isoAlpha2: 'BL', isoAlpha3: 'BLM', name: 'Saint Barthélemy' },
  { isoAlpha2: 'BM', isoAlpha3: 'BMU', name: 'Bermuda' },
  { isoAlpha2: 'BN', isoAlpha3: 'BRN', name: 'Brunei Darussalam' },
  { isoAlpha2: 'BO', isoAlpha3: 'BOL', name: 'Bolivia, Plurinational State of' },
  { isoAlpha2: 'BQ', isoAlpha3: 'BES', name: 'Bonaire, Sint Eustatius and Saba' },
  { isoAlpha2: 'BR', isoAlpha3: 'BRA', name: 'Brazil' },
  { isoAlpha2: 'BS', isoAlpha3: 'BHS', name: 'Bahamas' },
  { isoAlpha2: 'BT', isoAlpha3: 'BTN', name: 'Bhutan' },
  { isoAlpha2: 'BV', isoAlpha3: 'BVT', name: 'Bouvet Island' },
  { isoAlpha2: 'BW', isoAlpha3: 'BWA', name: 'Botswana' },
  { isoAlpha2: 'BY', isoAlpha3: 'BLR', name: 'Belarus' },
  { isoAlpha2: 'BZ', isoAlpha3: 'BLZ', name: 'Belize' },
  { isoAlpha2: 'CA', isoAlpha3: 'CAN', name: 'Canada' },
  { isoAlpha2: 'CC', isoAlpha3: 'CCK', name: 'Cocos (Keeling) Islands' },
  { isoAlpha2: 'CD', isoAlpha3: 'COD', name: 'Congo, Democratic Republic of the' },
  { isoAlpha2: 'CF', isoAlpha3: 'CAF', name: 'Central African Republic' },
  { isoAlpha2: 'CG', isoAlpha3: 'COG', name: 'Congo' },
  { isoAlpha2: 'CH', isoAlpha3: 'CHE', name: 'Switzerland' },
  { isoAlpha2: 'CI', isoAlpha3: 'CIV', name: "Côte d'Ivoire" },
  { isoAlpha2: 'CK', isoAlpha3: 'COK', name: 'Cook Islands' },
  { isoAlpha2: 'CL', isoAlpha3: 'CHL', name: 'Chile' },
  { isoAlpha2: 'CM', isoAlpha3: 'CMR', name: 'Cameroon' },
  { isoAlpha2: 'CN', isoAlpha3: 'CHN', name: 'China' },
  { isoAlpha2: 'CO', isoAlpha3: 'COL', name: 'Colombia' },
  { isoAlpha2: 'CR', isoAlpha3: 'CRI', name: 'Costa Rica' },
  { isoAlpha2: 'CU', isoAlpha3: 'CUB', name: 'Cuba' },
  { isoAlpha2: 'CV', isoAlpha3: 'CPV', name: 'Cabo Verde' },
  { isoAlpha2: 'CW', isoAlpha3: 'CUW', name: 'Curaçao' },
  { isoAlpha2: 'CX', isoAlpha3: 'CXR', name: 'Christmas Island' },
  { isoAlpha2: 'CY', isoAlpha3: 'CYP', name: 'Cyprus' },
  { isoAlpha2: 'CZ', isoAlpha3: 'CZE', name: 'Czechia' },
  { isoAlpha2: 'DE', isoAlpha3: 'DEU', name: 'Germany' },
  { isoAlpha2: 'DJ', isoAlpha3: 'DJI', name: 'Djibouti' },
  { isoAlpha2: 'DK', isoAlpha3: 'DNK', name: 'Denmark' },
  { isoAlpha2: 'DM', isoAlpha3: 'DMA', name: 'Dominica' },
  { isoAlpha2: 'DO', isoAlpha3: 'DOM', name: 'Dominican Republic' },
  { isoAlpha2: 'DZ', isoAlpha3: 'DZA', name: 'Algeria' },
  { isoAlpha2: 'EC', isoAlpha3: 'ECU', name: 'Ecuador' },
  { isoAlpha2: 'EE', isoAlpha3: 'EST', name: 'Estonia' },
  { isoAlpha2: 'EG', isoAlpha3: 'EGY', name: 'Egypt' },
  { isoAlpha2: 'EH', isoAlpha3: 'ESH', name: 'Western Sahara' },
  { isoAlpha2: 'ER', isoAlpha3: 'ERI', name: 'Eritrea' },
  { isoAlpha2: 'ES', isoAlpha3: 'ESP', name: 'Spain' },
  { isoAlpha2: 'ET', isoAlpha3: 'ETH', name: 'Ethiopia' },
  { isoAlpha2: 'FI', isoAlpha3: 'FIN', name: 'Finland' },
  { isoAlpha2: 'FJ', isoAlpha3: 'FJI', name: 'Fiji' },
  { isoAlpha2: 'FK', isoAlpha3: 'FLK', name: 'Falkland Islands (Malvinas)' },
  { isoAlpha2: 'FM', isoAlpha3: 'FSM', name: 'Micronesia, Federated States of' },
  { isoAlpha2: 'FO', isoAlpha3: 'FRO', name: 'Faroe Islands' },
  { isoAlpha2: 'FR', isoAlpha3: 'FRA', name: 'France' },
  { isoAlpha2: 'GA', isoAlpha3: 'GAB', name: 'Gabon' },
  { isoAlpha2: 'GB', isoAlpha3: 'GBR', name: 'United Kingdom of Great Britain and Northern Ireland' },
  { isoAlpha2: 'GD', isoAlpha3: 'GRD', name: 'Grenada' },
  { isoAlpha2: 'GE', isoAlpha3: 'GEO', name: 'Georgia' },
  { isoAlpha2: 'GF', isoAlpha3: 'GUF', name: 'French Guiana' },
  { isoAlpha2: 'GG', isoAlpha3: 'GGY', name: 'Guernsey' },
  { isoAlpha2: 'GH', isoAlpha3: 'GHA', name: 'Ghana' },
  { isoAlpha2: 'GI', isoAlpha3: 'GIB', name: 'Gibraltar' },
  { isoAlpha2: 'GL', isoAlpha3: 'GRL', name: 'Greenland' },
  { isoAlpha2: 'GM', isoAlpha3: 'GMB', name: 'Gambia' },
  { isoAlpha2: 'GN', isoAlpha3: 'GIN', name: 'Guinea' },
  { isoAlpha2: 'GP', isoAlpha3: 'GLP', name: 'Guadeloupe' },
  { isoAlpha2: 'GQ', isoAlpha3: 'GNQ', name: 'Equatorial Guinea' },
  { isoAlpha2: 'GR', isoAlpha3: 'GRC', name: 'Greece' },
  { isoAlpha2: 'GS', isoAlpha3: 'SGS', name: 'South Georgia and the South Sandwich Islands' },
  { isoAlpha2: 'GT', isoAlpha3: 'GTM', name: 'Guatemala' },
  { isoAlpha2: 'GU', isoAlpha3: 'GUM', name: 'Guam' },
  { isoAlpha2: 'GW', isoAlpha3: 'GNB', name: 'Guinea-Bissau' },
  { isoAlpha2: 'GY', isoAlpha3: 'GUY', name: 'Guyana' },
  { isoAlpha2: 'HK', isoAlpha3: 'HKG', name: 'Hong Kong' },
  { isoAlpha2: 'HM', isoAlpha3: 'HMD', name: 'Heard Island and McDonald Islands' },
  { isoAlpha2: 'HN', isoAlpha3: 'HND', name: 'Honduras' },
  { isoAlpha2: 'HR', isoAlpha3: 'HRV', name: 'Croatia' },
  { isoAlpha2: 'HT', isoAlpha3: 'HTI', name: 'Haiti' },
  { isoAlpha2: 'HU', isoAlpha3: 'HUN', name: 'Hungary' },
  { isoAlpha2: 'ID', isoAlpha3: 'IDN', name: 'Indonesia' },
  { isoAlpha2: 'IE', isoAlpha3: 'IRL', name: 'Ireland' },
  { isoAlpha2: 'IL', isoAlpha3: 'ISR', name: 'Israel' },
  { isoAlpha2: 'IM', isoAlpha3: 'IMN', name: 'Isle of Man' },
  { isoAlpha2: 'IN', isoAlpha3: 'IND', name: 'India' },
  { isoAlpha2: 'IO', isoAlpha3: 'IOT', name: 'British Indian Ocean Territory' },
  { isoAlpha2: 'IQ', isoAlpha3: 'IRQ', name: 'Iraq' },
  { isoAlpha2: 'IR', isoAlpha3: 'IRN', name: 'Iran, Islamic Republic of' },
  { isoAlpha2: 'IS', isoAlpha3: 'ISL', name: 'Iceland' },
  { isoAlpha2: 'IT', isoAlpha3: 'ITA', name: 'Italy' },
  { isoAlpha2: 'JE', isoAlpha3: 'JEY', name: 'Jersey' },
  { isoAlpha2: 'JM', isoAlpha3: 'JAM', name: 'Jamaica' },
  { isoAlpha2: 'JO', isoAlpha3: 'JOR', name: 'Jordan' },
  { isoAlpha2: 'JP', isoAlpha3: 'JPN', name: 'Japan' },
  { isoAlpha2: 'KE', isoAlpha3: 'KEN', name: 'Kenya' },
  { isoAlpha2: 'KG', isoAlpha3: 'KGZ', name: 'Kyrgyzstan' },
  { isoAlpha2: 'KH', isoAlpha3: 'KHM', name: 'Cambodia' },
  { isoAlpha2: 'KI', isoAlpha3: 'KIR', name: 'Kiribati' },
  { isoAlpha2: 'KM', isoAlpha3: 'COM', name: 'Comoros' },
  { isoAlpha2: 'KN', isoAlpha3: 'KNA', name: 'Saint Kitts and Nevis' },
  { isoAlpha2: 'KP', isoAlpha3: 'PRK', name: "Korea, Democratic People's Republic of" },
  { isoAlpha2: 'KR', isoAlpha3: 'KOR', name: 'Korea, Republic of' },
  { isoAlpha2: 'KW', isoAlpha3: 'KWT', name: 'Kuwait' },
  { isoAlpha2: 'KY', isoAlpha3: 'CYM', name: 'Cayman Islands' },
  { isoAlpha2: 'KZ', isoAlpha3: 'KAZ', name: 'Kazakhstan' },
  { isoAlpha2: 'LA', isoAlpha3: 'LAO', name: "Lao People's Democratic Republic" },
  { isoAlpha2: 'LB', isoAlpha3: 'LBN', name: 'Lebanon' },
  { isoAlpha2: 'LC', isoAlpha3: 'LCA', name: 'Saint Lucia' },
  { isoAlpha2: 'LI', isoAlpha3: 'LIE', name: 'Liechtenstein' },
  { isoAlpha2: 'LK', isoAlpha3: 'LKA', name: 'Sri Lanka' },
  { isoAlpha2: 'LR', isoAlpha3: 'LBR', name: 'Liberia' },
  { isoAlpha2: 'LS', isoAlpha3: 'LSO', name: 'Lesotho' },
  { isoAlpha2: 'LT', isoAlpha3: 'LTU', name: 'Lithuania' },
  { isoAlpha2: 'LU', isoAlpha3: 'LUX', name: 'Luxembourg' },
  { isoAlpha2: 'LV', isoAlpha3: 'LVA', name: 'Latvia' },
  { isoAlpha2: 'LY', isoAlpha3: 'LBY', name: 'Libya' },
  { isoAlpha2: 'MA', isoAlpha3: 'MAR', name: 'Morocco' },
  { isoAlpha2: 'MC', isoAlpha3: 'MCO', name: 'Monaco' },
  { isoAlpha2: 'MD', isoAlpha3: 'MDA', name: 'Moldova, Republic of' },
  { isoAlpha2: 'ME', isoAlpha3: 'MNE', name: 'Montenegro' },
  { isoAlpha2: 'MF', isoAlpha3: 'MAF', name: 'Saint Martin (French part)' },
  { isoAlpha2: 'MG', isoAlpha3: 'MDG', name: 'Madagascar' },
  { isoAlpha2: 'MH', isoAlpha3: 'MHL', name: 'Marshall Islands' },
  { isoAlpha2: 'MK', isoAlpha3: 'MKD', name: 'North Macedonia' },
  { isoAlpha2: 'ML', isoAlpha3: 'MLI', name: 'Mali' },
  { isoAlpha2: 'MM', isoAlpha3: 'MMR', name: 'Myanmar' },
  { isoAlpha2: 'MN', isoAlpha3: 'MNG', name: 'Mongolia' },
  { isoAlpha2: 'MO', isoAlpha3: 'MAC', name: 'Macao' },
  { isoAlpha2: 'MP', isoAlpha3: 'MNP', name: 'Northern Mariana Islands' },
  { isoAlpha2: 'MQ', isoAlpha3: 'MTQ', name: 'Martinique' },
  { isoAlpha2: 'MR', isoAlpha3: 'MRT', name: 'Mauritania' },
  { isoAlpha2: 'MS', isoAlpha3: 'MSR', name: 'Montserrat' },
  { isoAlpha2: 'MT', isoAlpha3: 'MLT', name: 'Malta' },
  { isoAlpha2: 'MU', isoAlpha3: 'MUS', name: 'Mauritius' },
  { isoAlpha2: 'MV', isoAlpha3: 'MDV', name: 'Maldives' },
  { isoAlpha2: 'MW', isoAlpha3: 'MWI', name: 'Malawi' },
  { isoAlpha2: 'MX', isoAlpha3: 'MEX', name: 'Mexico' },
  { isoAlpha2: 'MY', isoAlpha3: 'MYS', name: 'Malaysia' },
  { isoAlpha2: 'MZ', isoAlpha3: 'MOZ', name: 'Mozambique' },
  { isoAlpha2: 'NA', isoAlpha3: 'NAM', name: 'Namibia' },
  { isoAlpha2: 'NC', isoAlpha3: 'NCL', name: 'New Caledonia' },
  { isoAlpha2: 'NE', isoAlpha3: 'NER', name: 'Niger' },
  { isoAlpha2: 'NF', isoAlpha3: 'NFK', name: 'Norfolk Island' },
  { isoAlpha2: 'NG', isoAlpha3: 'NGA', name: 'Nigeria' },
  { isoAlpha2: 'NI', isoAlpha3: 'NIC', name: 'Nicaragua' },
  { isoAlpha2: 'NL', isoAlpha3: 'NLD', name: 'Netherlands, Kingdom of the' },
  { isoAlpha2: 'NO', isoAlpha3: 'NOR', name: 'Norway' },
  { isoAlpha2: 'NP', isoAlpha3: 'NPL', name: 'Nepal' },
  { isoAlpha2: 'NR', isoAlpha3: 'NRU', name: 'Nauru' },
  { isoAlpha2: 'NU', isoAlpha3: 'NIU', name: 'Niue' },
  { isoAlpha2: 'NZ', isoAlpha3: 'NZL', name: 'New Zealand' },
  { isoAlpha2: 'OM', isoAlpha3: 'OMN', name: 'Oman' },
  { isoAlpha2: 'PA', isoAlpha3: 'PAN', name: 'Panama' },
  { isoAlpha2: 'PE', isoAlpha3: 'PER', name: 'Peru' },
  { isoAlpha2: 'PF', isoAlpha3: 'PYF', name: 'French Polynesia' },
  { isoAlpha2: 'PG', isoAlpha3: 'PNG', name: 'Papua New Guinea' },
  { isoAlpha2: 'PH', isoAlpha3: 'PHL', name: 'Philippines' },
  { isoAlpha2: 'PK', isoAlpha3: 'PAK', name: 'Pakistan' },
  { isoAlpha2: 'PL', isoAlpha3: 'POL', name: 'Poland' },
  { isoAlpha2: 'PM', isoAlpha3: 'SPM', name: 'Saint Pierre and Miquelon' },
  { isoAlpha2: 'PN', isoAlpha3: 'PCN', name: 'Pitcairn' },
  { isoAlpha2: 'PR', isoAlpha3: 'PRI', name: 'Puerto Rico' },
  { isoAlpha2: 'PS', isoAlpha3: 'PSE', name: 'Palestine, State of' },
  { isoAlpha2: 'PT', isoAlpha3: 'PRT', name: 'Portugal' },
  { isoAlpha2: 'PW', isoAlpha3: 'PLW', name: 'Palau' },
  { isoAlpha2: 'PY', isoAlpha3: 'PRY', name: 'Paraguay' },
  { isoAlpha2: 'QA', isoAlpha3: 'QAT', name: 'Qatar' },
  { isoAlpha2: 'RE', isoAlpha3: 'REU', name: 'Réunion' },
  { isoAlpha2: 'RO', isoAlpha3: 'ROU', name: 'Romania' },
  { isoAlpha2: 'RS', isoAlpha3: 'SRB', name: 'Serbia' },
  { isoAlpha2: 'RU', isoAlpha3: 'RUS', name: 'Russian Federation' },
  { isoAlpha2: 'RW', isoAlpha3: 'RWA', name: 'Rwanda' },
  { isoAlpha2: 'SA', isoAlpha3: 'SAU', name: 'Saudi Arabia' },
  { isoAlpha2: 'SB', isoAlpha3: 'SLB', name: 'Solomon Islands' },
  { isoAlpha2: 'SC', isoAlpha3: 'SYC', name: 'Seychelles' },
  { isoAlpha2: 'SD', isoAlpha3: 'SDN', name: 'Sudan' },
  { isoAlpha2: 'SE', isoAlpha3: 'SWE', name: 'Sweden' },
  { isoAlpha2: 'SG', isoAlpha3: 'SGP', name: 'Singapore' },
  { isoAlpha2: 'SH', isoAlpha3: 'SHN', name: 'Saint Helena, Ascension and Tristan da Cunha' },
  { isoAlpha2: 'SI', isoAlpha3: 'SVN', name: 'Slovenia' },
  { isoAlpha2: 'SJ', isoAlpha3: 'SJM', name: 'Svalbard and Jan Mayen' },
  { isoAlpha2: 'SK', isoAlpha3: 'SVK', name: 'Slovakia' },
  { isoAlpha2: 'SL', isoAlpha3: 'SLE', name: 'Sierra Leone' },
  { isoAlpha2: 'SM', isoAlpha3: 'SMR', name: 'San Marino' },
  { isoAlpha2: 'SN', isoAlpha3: 'SEN', name: 'Senegal' },
  { isoAlpha2: 'SO', isoAlpha3: 'SOM', name: 'Somalia' },
  { isoAlpha2: 'SR', isoAlpha3: 'SUR', name: 'Suriname' },
  { isoAlpha2: 'SS', isoAlpha3: 'SSD', name: 'South Sudan' },
  { isoAlpha2: 'ST', isoAlpha3: 'STP', name: 'Sao Tome and Principe' },
  { isoAlpha2: 'SV', isoAlpha3: 'SLV', name: 'El Salvador' },
  { isoAlpha2: 'SX', isoAlpha3: 'SXM', name: 'Sint Maarten (Dutch part)' },
  { isoAlpha2: 'SY', isoAlpha3: 'SYR', name: 'Syrian Arab Republic' },
  { isoAlpha2: 'SZ', isoAlpha3: 'SWZ', name: 'Eswatini' },
  { isoAlpha2: 'TC', isoAlpha3: 'TCA', name: 'Turks and Caicos Islands' },
  { isoAlpha2: 'TD', isoAlpha3: 'TCD', name: 'Chad' },
  { isoAlpha2: 'TF', isoAlpha3: 'ATF', name: 'French Southern Territories' },
  { isoAlpha2: 'TG', isoAlpha3: 'TGO', name: 'Togo' },
  { isoAlpha2: 'TH', isoAlpha3: 'THA', name: 'Thailand' },
  { isoAlpha2: 'TJ', isoAlpha3: 'TJK', name: 'Tajikistan' },
  { isoAlpha2: 'TK', isoAlpha3: 'TKL', name: 'Tokelau' },
  { isoAlpha2: 'TL', isoAlpha3: 'TLS', name: 'Timor-Leste' },
  { isoAlpha2: 'TM', isoAlpha3: 'TKM', name: 'Turkmenistan' },
  { isoAlpha2: 'TN', isoAlpha3: 'TUN', name: 'Tunisia' },
  { isoAlpha2: 'TO', isoAlpha3: 'TON', name: 'Tonga' },
  { isoAlpha2: 'TR', isoAlpha3: 'TUR', name: 'Türkiye' },
  { isoAlpha2: 'TT', isoAlpha3: 'TTO', name: 'Trinidad and Tobago' },
  { isoAlpha2: 'TV', isoAlpha3: 'TUV', name: 'Tuvalu' },
  { isoAlpha2: 'TW', isoAlpha3: 'TWN', name: 'Taiwan, Province of China' },
  { isoAlpha2: 'TZ', isoAlpha3: 'TZA', name: 'Tanzania, United Republic of' },
  { isoAlpha2: 'UA', isoAlpha3: 'UKR', name: 'Ukraine' },
  { isoAlpha2: 'UG', isoAlpha3: 'UGA', name: 'Uganda' },
  { isoAlpha2: 'UM', isoAlpha3: 'UMI', name: 'United States Minor Outlying Islands' },
  { isoAlpha2: 'US', isoAlpha3: 'USA', name: 'United States of America' },
  { isoAlpha2: 'UY', isoAlpha3: 'URY', name: 'Uruguay' },
  { isoAlpha2: 'UZ', isoAlpha3: 'UZB', name: 'Uzbekistan' },
  { isoAlpha2: 'VA', isoAlpha3: 'VAT', name: 'Holy See' },
  { isoAlpha2: 'VC', isoAlpha3: 'VCT', name: 'Saint Vincent and the Grenadines' },
  { isoAlpha2: 'VE', isoAlpha3: 'VEN', name: 'Venezuela, Bolivarian Republic of' },
  { isoAlpha2: 'VG', isoAlpha3: 'VGB', name: 'Virgin Islands (British)' },
  { isoAlpha2: 'VI', isoAlpha3: 'VIR', name: 'Virgin Islands (U.S.)' },
  { isoAlpha2: 'VN', isoAlpha3: 'VNM', name: 'Viet Nam' },
  { isoAlpha2: 'VU', isoAlpha3: 'VUT', name: 'Vanuatu' },
  { isoAlpha2: 'WF', isoAlpha3: 'WLF', name: 'Wallis and Futuna' },
  { isoAlpha2: 'WS', isoAlpha3: 'WSM', name: 'Samoa' },
  { isoAlpha2: 'YE', isoAlpha3: 'YEM', name: 'Yemen' },
  { isoAlpha2: 'YT', isoAlpha3: 'MYT', name: 'Mayotte' },
  { isoAlpha2: 'ZA', isoAlpha3: 'ZAF', name: 'South Africa' },
  { isoAlpha2: 'ZM', isoAlpha3: 'ZMB', name: 'Zambia' },
  { isoAlpha2: 'ZW', isoAlpha3: 'ZWE', name: 'Zimbabwe' },
];

/** ISO 4217 alphabetic codes with ISO minor units. Phase 1 stores codes; it does not convert money. */
export const ISO_4217_CURRENCIES: ReadonlyArray<{ code: string; name: string; minorUnit: number }> = [
  { code: 'AED', name: 'UAE Dirham', minorUnit: 2 },
  { code: 'AFN', name: 'Afghani', minorUnit: 2 },
  { code: 'ALL', name: 'Lek', minorUnit: 2 },
  { code: 'AMD', name: 'Armenian Dram', minorUnit: 2 },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', minorUnit: 2 },
  { code: 'AOA', name: 'Kwanza', minorUnit: 2 },
  { code: 'ARS', name: 'Argentine Peso', minorUnit: 2 },
  { code: 'AUD', name: 'Australian Dollar', minorUnit: 2 },
  { code: 'AWG', name: 'Aruban Florin', minorUnit: 2 },
  { code: 'AZN', name: 'Azerbaijan Manat', minorUnit: 2 },
  { code: 'BAM', name: 'Convertible Mark', minorUnit: 2 },
  { code: 'BBD', name: 'Barbados Dollar', minorUnit: 2 },
  { code: 'BDT', name: 'Taka', minorUnit: 2 },
  { code: 'BGN', name: 'Bulgarian Lev', minorUnit: 2 },
  { code: 'BHD', name: 'Bahraini Dinar', minorUnit: 3 },
  { code: 'BIF', name: 'Burundi Franc', minorUnit: 0 },
  { code: 'BMD', name: 'Bermudian Dollar', minorUnit: 2 },
  { code: 'BND', name: 'Brunei Dollar', minorUnit: 2 },
  { code: 'BOB', name: 'Boliviano', minorUnit: 2 },
  { code: 'BRL', name: 'Brazilian Real', minorUnit: 2 },
  { code: 'BSD', name: 'Bahamian Dollar', minorUnit: 2 },
  { code: 'BTN', name: 'Ngultrum', minorUnit: 2 },
  { code: 'BWP', name: 'Pula', minorUnit: 2 },
  { code: 'BYN', name: 'Belarusian Ruble', minorUnit: 2 },
  { code: 'BZD', name: 'Belize Dollar', minorUnit: 2 },
  { code: 'CAD', name: 'Canadian Dollar', minorUnit: 2 },
  { code: 'CDF', name: 'Congolese Franc', minorUnit: 2 },
  { code: 'CHF', name: 'Swiss Franc', minorUnit: 2 },
  { code: 'CLP', name: 'Chilean Peso', minorUnit: 0 },
  { code: 'CNY', name: 'Yuan Renminbi', minorUnit: 2 },
  { code: 'COP', name: 'Colombian Peso', minorUnit: 2 },
  { code: 'CRC', name: 'Costa Rican Colon', minorUnit: 2 },
  { code: 'CUP', name: 'Cuban Peso', minorUnit: 2 },
  { code: 'CVE', name: 'Cabo Verde Escudo', minorUnit: 2 },
  { code: 'CZK', name: 'Czech Koruna', minorUnit: 2 },
  { code: 'DJF', name: 'Djibouti Franc', minorUnit: 0 },
  { code: 'DKK', name: 'Danish Krone', minorUnit: 2 },
  { code: 'DOP', name: 'Dominican Peso', minorUnit: 2 },
  { code: 'DZD', name: 'Algerian Dinar', minorUnit: 2 },
  { code: 'EGP', name: 'Egyptian Pound', minorUnit: 2 },
  { code: 'ERN', name: 'Nakfa', minorUnit: 2 },
  { code: 'ETB', name: 'Ethiopian Birr', minorUnit: 2 },
  { code: 'EUR', name: 'Euro', minorUnit: 2 },
  { code: 'FJD', name: 'Fiji Dollar', minorUnit: 2 },
  { code: 'FKP', name: 'Falkland Islands Pound', minorUnit: 2 },
  { code: 'GBP', name: 'Pound Sterling', minorUnit: 2 },
  { code: 'GEL', name: 'Lari', minorUnit: 2 },
  { code: 'GHS', name: 'Ghana Cedi', minorUnit: 2 },
  { code: 'GIP', name: 'Gibraltar Pound', minorUnit: 2 },
  { code: 'GMD', name: 'Dalasi', minorUnit: 2 },
  { code: 'GNF', name: 'Guinean Franc', minorUnit: 0 },
  { code: 'GTQ', name: 'Quetzal', minorUnit: 2 },
  { code: 'GYD', name: 'Guyana Dollar', minorUnit: 2 },
  { code: 'HKD', name: 'Hong Kong Dollar', minorUnit: 2 },
  { code: 'HNL', name: 'Lempira', minorUnit: 2 },
  { code: 'HTG', name: 'Gourde', minorUnit: 2 },
  { code: 'HUF', name: 'Forint', minorUnit: 2 },
  { code: 'IDR', name: 'Rupiah', minorUnit: 2 },
  { code: 'ILS', name: 'New Israeli Shekel', minorUnit: 2 },
  { code: 'INR', name: 'Indian Rupee', minorUnit: 2 },
  { code: 'IQD', name: 'Iraqi Dinar', minorUnit: 3 },
  { code: 'IRR', name: 'Iranian Rial', minorUnit: 2 },
  { code: 'ISK', name: 'Iceland Krona', minorUnit: 0 },
  { code: 'JMD', name: 'Jamaican Dollar', minorUnit: 2 },
  { code: 'JOD', name: 'Jordanian Dinar', minorUnit: 3 },
  { code: 'JPY', name: 'Yen', minorUnit: 0 },
  { code: 'KES', name: 'Kenyan Shilling', minorUnit: 2 },
  { code: 'KGS', name: 'Som', minorUnit: 2 },
  { code: 'KHR', name: 'Riel', minorUnit: 2 },
  { code: 'KMF', name: 'Comorian Franc', minorUnit: 0 },
  { code: 'KPW', name: 'North Korean Won', minorUnit: 2 },
  { code: 'KRW', name: 'Won', minorUnit: 0 },
  { code: 'KWD', name: 'Kuwaiti Dinar', minorUnit: 3 },
  { code: 'KYD', name: 'Cayman Islands Dollar', minorUnit: 2 },
  { code: 'KZT', name: 'Tenge', minorUnit: 2 },
  { code: 'LAK', name: 'Lao Kip', minorUnit: 2 },
  { code: 'LBP', name: 'Lebanese Pound', minorUnit: 2 },
  { code: 'LKR', name: 'Sri Lanka Rupee', minorUnit: 2 },
  { code: 'LRD', name: 'Liberian Dollar', minorUnit: 2 },
  { code: 'LSL', name: 'Loti', minorUnit: 2 },
  { code: 'LYD', name: 'Libyan Dinar', minorUnit: 3 },
  { code: 'MAD', name: 'Moroccan Dirham', minorUnit: 2 },
  { code: 'MDL', name: 'Moldovan Leu', minorUnit: 2 },
  { code: 'MGA', name: 'Malagasy Ariary', minorUnit: 2 },
  { code: 'MKD', name: 'Denar', minorUnit: 2 },
  { code: 'MMK', name: 'Kyat', minorUnit: 2 },
  { code: 'MNT', name: 'Tugrik', minorUnit: 2 },
  { code: 'MOP', name: 'Pataca', minorUnit: 2 },
  { code: 'MRU', name: 'Ouguiya', minorUnit: 2 },
  { code: 'MUR', name: 'Mauritius Rupee', minorUnit: 2 },
  { code: 'MVR', name: 'Rufiyaa', minorUnit: 2 },
  { code: 'MWK', name: 'Malawi Kwacha', minorUnit: 2 },
  { code: 'MXN', name: 'Mexican Peso', minorUnit: 2 },
  { code: 'MYR', name: 'Malaysian Ringgit', minorUnit: 2 },
  { code: 'MZN', name: 'Mozambique Metical', minorUnit: 2 },
  { code: 'NAD', name: 'Namibia Dollar', minorUnit: 2 },
  { code: 'NGN', name: 'Naira', minorUnit: 2 },
  { code: 'NIO', name: 'Cordoba Oro', minorUnit: 2 },
  { code: 'NOK', name: 'Norwegian Krone', minorUnit: 2 },
  { code: 'NPR', name: 'Nepalese Rupee', minorUnit: 2 },
  { code: 'NZD', name: 'New Zealand Dollar', minorUnit: 2 },
  { code: 'OMR', name: 'Rial Omani', minorUnit: 3 },
  { code: 'PAB', name: 'Balboa', minorUnit: 2 },
  { code: 'PEN', name: 'Sol', minorUnit: 2 },
  { code: 'PGK', name: 'Kina', minorUnit: 2 },
  { code: 'PHP', name: 'Philippine Peso', minorUnit: 2 },
  { code: 'PKR', name: 'Pakistan Rupee', minorUnit: 2 },
  { code: 'PLN', name: 'Zloty', minorUnit: 2 },
  { code: 'PYG', name: 'Guarani', minorUnit: 0 },
  { code: 'QAR', name: 'Qatari Rial', minorUnit: 2 },
  { code: 'RON', name: 'Romanian Leu', minorUnit: 2 },
  { code: 'RSD', name: 'Serbian Dinar', minorUnit: 2 },
  { code: 'RUB', name: 'Russian Ruble', minorUnit: 2 },
  { code: 'RWF', name: 'Rwanda Franc', minorUnit: 0 },
  { code: 'SAR', name: 'Saudi Riyal', minorUnit: 2 },
  { code: 'SBD', name: 'Solomon Islands Dollar', minorUnit: 2 },
  { code: 'SCR', name: 'Seychelles Rupee', minorUnit: 2 },
  { code: 'SDG', name: 'Sudanese Pound', minorUnit: 2 },
  { code: 'SEK', name: 'Swedish Krona', minorUnit: 2 },
  { code: 'SGD', name: 'Singapore Dollar', minorUnit: 2 },
  { code: 'SHP', name: 'Saint Helena Pound', minorUnit: 2 },
  { code: 'SLE', name: 'Leone', minorUnit: 2 },
  { code: 'SOS', name: 'Somali Shilling', minorUnit: 2 },
  { code: 'SRD', name: 'Surinam Dollar', minorUnit: 2 },
  { code: 'SSP', name: 'South Sudanese Pound', minorUnit: 2 },
  { code: 'STN', name: 'Dobra', minorUnit: 2 },
  { code: 'SVC', name: 'El Salvador Colon', minorUnit: 2 },
  { code: 'SYP', name: 'Syrian Pound', minorUnit: 2 },
  { code: 'SZL', name: 'Lilangeni', minorUnit: 2 },
  { code: 'THB', name: 'Baht', minorUnit: 2 },
  { code: 'TJS', name: 'Somoni', minorUnit: 2 },
  { code: 'TMT', name: 'Turkmenistan New Manat', minorUnit: 2 },
  { code: 'TND', name: 'Tunisian Dinar', minorUnit: 3 },
  { code: 'TOP', name: 'Pa’anga', minorUnit: 2 },
  { code: 'TRY', name: 'Turkish Lira', minorUnit: 2 },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', minorUnit: 2 },
  { code: 'TWD', name: 'New Taiwan Dollar', minorUnit: 2 },
  { code: 'TZS', name: 'Tanzanian Shilling', minorUnit: 2 },
  { code: 'UAH', name: 'Hryvnia', minorUnit: 2 },
  { code: 'UGX', name: 'Uganda Shilling', minorUnit: 0 },
  { code: 'USD', name: 'US Dollar', minorUnit: 2 },
  { code: 'UYU', name: 'Peso Uruguayo', minorUnit: 2 },
  { code: 'UZS', name: 'Uzbekistan Sum', minorUnit: 2 },
  { code: 'VES', name: 'Bolívar Soberano', minorUnit: 2 },
  { code: 'VND', name: 'Dong', minorUnit: 0 },
  { code: 'VUV', name: 'Vatu', minorUnit: 0 },
  { code: 'WST', name: 'Tala', minorUnit: 2 },
  { code: 'XAF', name: 'CFA Franc BEAC', minorUnit: 0 },
  { code: 'XCD', name: 'East Caribbean Dollar', minorUnit: 2 },
  { code: 'XOF', name: 'CFA Franc BCEAO', minorUnit: 0 },
  { code: 'XPF', name: 'CFP Franc', minorUnit: 0 },
  { code: 'YER', name: 'Yemeni Rial', minorUnit: 2 },
  { code: 'ZAR', name: 'Rand', minorUnit: 2 },
  { code: 'ZMW', name: 'Zambian Kwacha', minorUnit: 2 },
  { code: 'ZWG', name: 'Zimbabwe Gold', minorUnit: 2 },
];
